/** Auto-generated by scripts/collect/export-portraits.mjs */

export type CharacterImageSet = {
  portrait: string;
  art?: string;
};

export const CHARACTER_IMAGES: Record<string, CharacterImageSet> = {
  "crimson-falcon": {
    "portrait": "/characters/crimson-falcon.webp",
    "art": "/characters/crimson-falcon-art.webp"
  },
  "ka-archer": {
    "portrait": "/characters/ka-archer.webp",
    "art": "/characters/ka-archer-art.webp"
  },
  "ka-fire-conjurer": {
    "portrait": "/characters/ka-fire-conjurer.webp",
    "art": "/characters/ka-fire-conjurer-art.webp"
  },
  "ka-light-conjurer": {
    "portrait": "/characters/ka-light-conjurer.webp",
    "art": "/characters/ka-light-conjurer-art.webp"
  },
  "knighted-pikeman": {
    "portrait": "/characters/knighted-pikeman.webp",
    "art": "/characters/knighted-pikeman-art.webp"
  },
  "maitha": {
    "portrait": "/characters/maitha.webp",
    "art": "/characters/maitha-art.webp"
  },
  "outlaw-axeman": {
    "portrait": "/characters/outlaw-axeman.webp",
    "art": "/characters/outlaw-axeman-art.webp"
  },
  "recruited-assassin": {
    "portrait": "/characters/recruited-assassin.webp",
    "art": "/characters/recruited-assassin-art.webp"
  },
  "recruited-guard": {
    "portrait": "/characters/recruited-guard.webp",
    "art": "/characters/recruited-guard-art.webp"
  },
  "recruited-pikeman": {
    "portrait": "/characters/recruited-pikeman.webp",
    "art": "/characters/recruited-pikeman-art.webp"
  }
};

export function getCharacterImage(slug: string): CharacterImageSet | undefined {
  return CHARACTER_IMAGES[slug];
}

export function hasCharacterPortrait(slug: string): boolean {
  return Boolean(CHARACTER_IMAGES[slug]?.portrait);
}
