import type { Character, Role, Tier, SkillRow } from "@/types/character";

/** Auto-generated by scripts/collect/apply-device-ocr.mjs — client skill tooltips. */
export type DeviceOcrPartial = Partial<Character> & { slug: string; name: string; confidence?: string; source?: string };

export const DEVICE_OCR_REFINED: DeviceOcrPartial[] = [
  {
    "slug": "crimson-falcon",
    "name": "Crimson Falcon",
    "rarity": "Epic",
    "role": "Breaker",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Epic melee breaker with multi-hit, crit buff skill, and Instant teleport steal (Shadow Gait).",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Epic melee breaker with multi-hit, crit buff skill, and Instant teleport steal (Shadow Gait).",
    "build": {
      "basicAttack": "Armor-Piercing Strike",
      "reaction": "Vital Guard",
      "skills": [
        "Flurry of Stabs",
        "Shadow Gait",
        "Inspiration of Comrades"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Armor-Piercing Strike",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals physical DMG 2 times and inflicts debuffs on the target. Melee range 1-1."
      },
      {
        "name": "Vital Guard",
        "kind": "Reaction",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) When hit by an active attack, DMG taken decreased. If injured, gains a buff for 1 turn. Up to 1 time per round."
      },
      {
        "name": "Inspiration of Comrades",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Passive) At start of turn, if 2+ allies within 2 tiles, gains a buff for 1 turn. When hit with 2+ allies nearby, decreases DMG taken."
      },
      {
        "name": "Flurry of Stabs",
        "kind": "Active",
        "stars": 5,
        "nrg": "2",
        "cd": "—",
        "note": "Class Skill NRG 2",
        "description": "(Physical DMG) Deals 45% DMG 3 times. When attacking, Crit increases by 20%. Melee range 1-1."
      },
      {
        "name": "Shadow Gait",
        "kind": "Active",
        "stars": 5,
        "nrg": "1",
        "cd": "3",
        "note": "Class Skill NRG 1 CD 3",
        "description": "(Support) [Instant] Teleports behind the enemy and steals 1 random Attribute Buff from the target. Range 1-1."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "ka-archer",
    "name": "K.A. Archer",
    "rarity": "Rare",
    "role": "Breaker",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare archer with covering fire and positioning passive.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare archer with covering fire and positioning passive.",
    "build": {
      "basicAttack": "Curved Shot",
      "reaction": "Defense (AoE)",
      "skills": [
        "Covering Shot",
        "Full Draw",
        "Dharana"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Curved Shot",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Fires a projectile dealing Physical DMG. Ranged 2-3."
      },
      {
        "name": "Defense (AoE)",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) When hit by active AoE, reduces DMG taken."
      },
      {
        "name": "Full Draw",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) After use, basic attack DMG increases; NRG not recovered at end of turn."
      },
      {
        "name": "Dharana",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) At start of turn, if no enemies within 2 tiles, gains a buff for 1 turn."
      },
      {
        "name": "Covering Shot",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Performs covering fire against nearby enemies, up to 2 times per round."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "ka-fire-conjurer",
    "name": "K.A. Fire Conjurer",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare Iria fire mage with Fire Pillar AoE and faction aura.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare Iria fire mage with Fire Pillar AoE and faction aura.",
    "build": {
      "basicAttack": "Energy Wave",
      "reaction": "Endure",
      "skills": [
        "Fire Pillar",
        "Potential Burst",
        "Battle Flag of Iria"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Energy Wave",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals 80% Magical DMG. Ranged 1-2."
      },
      {
        "name": "Endure",
        "kind": "Reaction",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Takes less DoT."
      },
      {
        "name": "Fire Pillar",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Magical DMG) Selects location, deals 70% fire AoE to all enemies within 1 tile. Range 1-3."
      },
      {
        "name": "Potential Burst",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Grants buffs, dispels debuffs, immunity for turns. Range 0-3."
      },
      {
        "name": "Battle Flag of Iria",
        "kind": "Aura",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Leader's Aura) For all Iria allies, increases ATK and DEF."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "ka-light-conjurer",
    "name": "K.A. Light Conjurer",
    "rarity": "Rare",
    "role": "Watcher",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare Union healer/mage with Sanction dispel and Healing Spell.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare Union healer/mage with Sanction dispel and Healing Spell.",
    "build": {
      "basicAttack": "Energy Wave",
      "reaction": "Endure",
      "skills": [
        "Healing Spell",
        "Sanction",
        "Regenerate"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Energy Wave",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals 80% Magical DMG. Ranged 1-2."
      },
      {
        "name": "Endure",
        "kind": "Reaction",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Takes less DoT."
      },
      {
        "name": "Regenerate",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) End of turn: heals lowest-HP ally within 3 tiles by % of M.ATK."
      },
      {
        "name": "Sanction",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Magical DMG) Single-target 150% DMG; after attack dispels 2 buffs. Ranged 1-2."
      },
      {
        "name": "Healing Spell",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Healing) Heals target by M.ATK and dispels 1 debuff. Range 0-2."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "knighted-pikeman",
    "name": "Knighted Pikeman",
    "rarity": "Epic",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Epic frontline pikeman with Preempt counter and Crescendo Combo.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Epic frontline pikeman with Preempt counter and Crescendo Combo.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Preempt",
      "skills": [
        "Crescendo Combo",
        "Parry",
        "Knightly Spirit"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals Physical DMG. Melee 1-1."
      },
      {
        "name": "Preempt",
        "kind": "Reaction",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Before active attack from front/side, Strike Back up to 1/round."
      },
      {
        "name": "Parry",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Before physical melee attack, faces attacker and adds P.ATK to P.DEF."
      },
      {
        "name": "Crescendo Combo",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target, dispels 2 buffs, then Pursuit dealing DMG. Range 1-1."
      },
      {
        "name": "Knightly Spirit",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Increases ATK when attacking from front; increases DEF when attacked from front."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "maitha",
    "name": "Maitha",
    "rarity": "Legendary",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Starter Defender captured from live client on Pixel 7. Skill tooltips include NRG/CD for class skills.",
    "pros": [
      "Team heal + ATK/P.DEF buffs",
      "Block and Counter reaction",
      "Knockback tools"
    ],
    "howToUse": "Open with Come On, Everybody! for party sustain/buffs; use Combo/Charge for chip and knockback.",
    "build": {
      "basicAttack": "Powerful Attack",
      "reaction": "Block and Counter",
      "skills": [
        "Come On, Everybody!",
        "Maitha's Combo",
        "Maitha's Charge"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Powerful Attack",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals 110% Physical DMG. Melee range 1-1."
      },
      {
        "name": "Block and Counter",
        "kind": "Reaction",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Reaction) When receiving a melee attack from the front or side, 100% chance to trigger Block. Leads to Strike Back with basic attack dealing 70% physical DMG. 1 time per round."
      },
      {
        "name": "Come On, Everybody!",
        "kind": "Active",
        "stars": 5,
        "nrg": "3",
        "cd": "—",
        "note": "Class Skill NRG 3",
        "description": "(Support) Restores 20% HP and grants ATK I and P.DEF I to all allies within 3 tiles. Takes physical attacks from the enemy for allies within 2 tiles for 2 turns."
      },
      {
        "name": "Maitha's Combo",
        "kind": "Active",
        "stars": 4,
        "nrg": "2",
        "cd": "4",
        "note": "Class Skill NRG 2 CD 4",
        "description": "(Physical DMG) Deals 20% DMG 1 time, 50% DMG 3 times, and knocks the target back by 2 tiles. Melee range 1-1."
      },
      {
        "name": "Maitha's Charge",
        "kind": "Active",
        "stars": 4,
        "nrg": "1",
        "cd": "5",
        "note": "Class Skill NRG 1 CD 5",
        "description": "(Physical DMG) Charges at 1 enemy within a cross-shaped range, dealing 130% DMG and knocking the target back by 2 tiles. Range 1-3."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "outlaw-axeman",
    "name": "Outlaw Axeman",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare axeman with AoE heal-reduction whirlwind.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare axeman with AoE heal-reduction whirlwind.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Defense (Back Attack)",
      "skills": [
        "Tearing Whirlwind",
        "Powerful Throw",
        "Shield Break"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals Physical DMG. Melee range 1-1."
      },
      {
        "name": "Defense (Back Attack)",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) Reduces DMG taken from active attacks; additional reduction vs back attacks."
      },
      {
        "name": "Tearing Whirlwind",
        "kind": "Active",
        "stars": 5,
        "nrg": "2",
        "cd": "3",
        "note": "Class Skill NRG 2 CD 3",
        "description": "(Physical DMG) Deals 90% AoE DMG to all enemies within 1-tile radius and inflicts Decreased Healing Received for 2 turns."
      },
      {
        "name": "Powerful Throw",
        "kind": "Active",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Physical DMG) Single-target ranged attack. Range 1-2."
      },
      {
        "name": "Shield Break",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Passive) Increases ATK when attacking enemies with a shield."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "medium",
    "source": "device-ocr"
  },
  {
    "slug": "recruited-assassin",
    "name": "Recruited Assassin",
    "rarity": "Rare",
    "role": "Breaker",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare assassin with pull (Hookshot) and multi-hit basic.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare assassin with pull (Hookshot) and multi-hit basic.",
    "build": {
      "basicAttack": "Dual Blade Strike",
      "reaction": "Counterattack",
      "skills": [
        "Hookshot",
        "Hunting Impulse",
        "Fancy Footwork"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Dual Blade Strike",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals physical DMG 2 times. Melee range 1-1."
      },
      {
        "name": "Counterattack",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) When hit by active attack from front or side, performs basic attack if attacker in range, up to 1/round."
      },
      {
        "name": "Hunting Impulse",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target. Crit increases before attack. If target defeated, recovers 3 NRG. Melee 1-1."
      },
      {
        "name": "Hookshot",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Debuff) Selects 1 enemy in cross range, drags to self, inflicts debuff 1 turn. Range 1-4."
      },
      {
        "name": "Fancy Footwork",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Takes less AoE DMG and gains dodge attempts for turns."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  },
  {
    "slug": "recruited-guard",
    "name": "Recruited Guard",
    "rarity": "Rare",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare frontline guard with party physical cover (Global Guard).",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare frontline guard with party physical cover (Global Guard).",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Front Defense",
      "skills": [
        "Global Guard",
        "Defensive Stance",
        "Knock-Out Blow"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals Physical DMG. Range 1-1."
      },
      {
        "name": "Front Defense",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) When hit by an active attack from the front, DMG taken decreased."
      },
      {
        "name": "Defensive Stance",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Support) Gains a shield based on HP and a buff for 2 turns."
      },
      {
        "name": "Global Guard",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Support) Takes physical attacks for all other allies within 2 tiles. Gains buffs for 3 turns when activated."
      },
      {
        "name": "Knock-Out Blow",
        "kind": "Active",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Physical DMG) Single-target attack dealing DMG and inflicting a debuff for 1 turn. Range 1-1."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "medium",
    "source": "device-ocr"
  },
  {
    "slug": "recruited-pikeman",
    "name": "Recruited Pikeman",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare pikeman with line AoE shieldbreak.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare pikeman with line AoE shieldbreak.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Counterattack",
      "skills": [
        "Shieldbreak Jab",
        "Crumbling Smash",
        "Rupture Armor"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals Physical DMG. Range 1-1."
      },
      {
        "name": "Counterattack",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Front/side hit triggers basic attack counter, 1/round."
      },
      {
        "name": "Shieldbreak Jab",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) AoE in target direction up to 4 tiles, inflicts debuff 2 turns."
      },
      {
        "name": "Crumbling Smash",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target. Gains a buff before attacking. Range 1-1."
      },
      {
        "name": "Rupture Armor",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Chance to inflict armor-break debuff for 2 turns before single-target attack."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "confidence": "high",
    "source": "device-ocr"
  }
] as DeviceOcrPartial[];

/** Full Character rows for slugs not present in rawCharacters seed. */
export const DEVICE_OCR_CHARACTERS: Character[] = [
  {
    "slug": "crimson-falcon",
    "name": "Crimson Falcon",
    "rarity": "Epic",
    "role": "Breaker",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Epic melee breaker with multi-hit, crit buff skill, and Instant teleport steal (Shadow Gait).",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Epic melee breaker with multi-hit, crit buff skill, and Instant teleport steal (Shadow Gait).",
    "build": {
      "basicAttack": "Armor-Piercing Strike",
      "reaction": "Vital Guard",
      "skills": [
        "Flurry of Stabs",
        "Shadow Gait",
        "Inspiration of Comrades"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Armor-Piercing Strike",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals physical DMG 2 times and inflicts debuffs on the target. Melee range 1-1."
      },
      {
        "name": "Vital Guard",
        "kind": "Reaction",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) When hit by an active attack, DMG taken decreased. If injured, gains a buff for 1 turn. Up to 1 time per round."
      },
      {
        "name": "Inspiration of Comrades",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Passive) At start of turn, if 2+ allies within 2 tiles, gains a buff for 1 turn. When hit with 2+ allies nearby, decreases DMG taken."
      },
      {
        "name": "Flurry of Stabs",
        "kind": "Active",
        "stars": 5,
        "nrg": "2",
        "cd": "—",
        "note": "Class Skill NRG 2",
        "description": "(Physical DMG) Deals 45% DMG 3 times. When attacking, Crit increases by 20%. Melee range 1-1."
      },
      {
        "name": "Shadow Gait",
        "kind": "Active",
        "stars": 5,
        "nrg": "1",
        "cd": "3",
        "note": "Class Skill NRG 1 CD 3",
        "description": "(Support) [Instant] Teleports behind the enemy and steals 1 random Attribute Buff from the target. Range 1-1."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "B",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "ka-archer",
    "name": "K.A. Archer",
    "rarity": "Rare",
    "role": "Breaker",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare archer with covering fire and positioning passive.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare archer with covering fire and positioning passive.",
    "build": {
      "basicAttack": "Curved Shot",
      "reaction": "Defense (AoE)",
      "skills": [
        "Covering Shot",
        "Full Draw",
        "Dharana"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Curved Shot",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Fires a projectile dealing Physical DMG. Ranged 2-3."
      },
      {
        "name": "Defense (AoE)",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) When hit by active AoE, reduces DMG taken."
      },
      {
        "name": "Full Draw",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) After use, basic attack DMG increases; NRG not recovered at end of turn."
      },
      {
        "name": "Dharana",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) At start of turn, if no enemies within 2 tiles, gains a buff for 1 turn."
      },
      {
        "name": "Covering Shot",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Performs covering fire against nearby enemies, up to 2 times per round."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "ka-fire-conjurer",
    "name": "K.A. Fire Conjurer",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare Iria fire mage with Fire Pillar AoE and faction aura.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare Iria fire mage with Fire Pillar AoE and faction aura.",
    "build": {
      "basicAttack": "Energy Wave",
      "reaction": "Endure",
      "skills": [
        "Fire Pillar",
        "Potential Burst",
        "Battle Flag of Iria"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Energy Wave",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals 80% Magical DMG. Ranged 1-2."
      },
      {
        "name": "Endure",
        "kind": "Reaction",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Takes less DoT."
      },
      {
        "name": "Fire Pillar",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Magical DMG) Selects location, deals 70% fire AoE to all enemies within 1 tile. Range 1-3."
      },
      {
        "name": "Potential Burst",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Grants buffs, dispels debuffs, immunity for turns. Range 0-3."
      },
      {
        "name": "Battle Flag of Iria",
        "kind": "Aura",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Leader's Aura) For all Iria allies, increases ATK and DEF."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "ka-light-conjurer",
    "name": "K.A. Light Conjurer",
    "rarity": "Rare",
    "role": "Watcher",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare Union healer/mage with Sanction dispel and Healing Spell.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare Union healer/mage with Sanction dispel and Healing Spell.",
    "build": {
      "basicAttack": "Energy Wave",
      "reaction": "Endure",
      "skills": [
        "Healing Spell",
        "Sanction",
        "Regenerate"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Energy Wave",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals 80% Magical DMG. Ranged 1-2."
      },
      {
        "name": "Endure",
        "kind": "Reaction",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Takes less DoT."
      },
      {
        "name": "Regenerate",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) End of turn: heals lowest-HP ally within 3 tiles by % of M.ATK."
      },
      {
        "name": "Sanction",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Magical DMG) Single-target 150% DMG; after attack dispels 2 buffs. Ranged 1-2."
      },
      {
        "name": "Healing Spell",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Healing) Heals target by M.ATK and dispels 1 debuff. Range 0-2."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "knighted-pikeman",
    "name": "Knighted Pikeman",
    "rarity": "Epic",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Epic frontline pikeman with Preempt counter and Crescendo Combo.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Epic frontline pikeman with Preempt counter and Crescendo Combo.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Preempt",
      "skills": [
        "Crescendo Combo",
        "Parry",
        "Knightly Spirit"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals Physical DMG. Melee 1-1."
      },
      {
        "name": "Preempt",
        "kind": "Reaction",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Before active attack from front/side, Strike Back up to 1/round."
      },
      {
        "name": "Parry",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Before physical melee attack, faces attacker and adds P.ATK to P.DEF."
      },
      {
        "name": "Crescendo Combo",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target, dispels 2 buffs, then Pursuit dealing DMG. Range 1-1."
      },
      {
        "name": "Knightly Spirit",
        "kind": "Passive",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Increases ATK when attacking from front; increases DEF when attacked from front."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "B",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "maitha",
    "name": "Maitha",
    "rarity": "Legendary",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Starter Defender captured from live client on Pixel 7. Skill tooltips include NRG/CD for class skills.",
    "pros": [
      "Team heal + ATK/P.DEF buffs",
      "Block and Counter reaction",
      "Knockback tools"
    ],
    "howToUse": "Open with Come On, Everybody! for party sustain/buffs; use Combo/Charge for chip and knockback.",
    "build": {
      "basicAttack": "Powerful Attack",
      "reaction": "Block and Counter",
      "skills": [
        "Come On, Everybody!",
        "Maitha's Combo",
        "Maitha's Charge"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Powerful Attack",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals 110% Physical DMG. Melee range 1-1."
      },
      {
        "name": "Block and Counter",
        "kind": "Reaction",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Reaction) When receiving a melee attack from the front or side, 100% chance to trigger Block. Leads to Strike Back with basic attack dealing 70% physical DMG. 1 time per round."
      },
      {
        "name": "Come On, Everybody!",
        "kind": "Active",
        "stars": 5,
        "nrg": "3",
        "cd": "—",
        "note": "Class Skill NRG 3",
        "description": "(Support) Restores 20% HP and grants ATK I and P.DEF I to all allies within 3 tiles. Takes physical attacks from the enemy for allies within 2 tiles for 2 turns."
      },
      {
        "name": "Maitha's Combo",
        "kind": "Active",
        "stars": 4,
        "nrg": "2",
        "cd": "4",
        "note": "Class Skill NRG 2 CD 4",
        "description": "(Physical DMG) Deals 20% DMG 1 time, 50% DMG 3 times, and knocks the target back by 2 tiles. Melee range 1-1."
      },
      {
        "name": "Maitha's Charge",
        "kind": "Active",
        "stars": 4,
        "nrg": "1",
        "cd": "5",
        "note": "Class Skill NRG 1 CD 5",
        "description": "(Physical DMG) Charges at 1 enemy within a cross-shaped range, dealing 130% DMG and knocking the target back by 2 tiles. Range 1-3."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "A",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "outlaw-axeman",
    "name": "Outlaw Axeman",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare axeman with AoE heal-reduction whirlwind.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare axeman with AoE heal-reduction whirlwind.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Defense (Back Attack)",
      "skills": [
        "Tearing Whirlwind",
        "Powerful Throw",
        "Shield Break"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals Physical DMG. Melee range 1-1."
      },
      {
        "name": "Defense (Back Attack)",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) Reduces DMG taken from active attacks; additional reduction vs back attacks."
      },
      {
        "name": "Tearing Whirlwind",
        "kind": "Active",
        "stars": 5,
        "nrg": "2",
        "cd": "3",
        "note": "Class Skill NRG 2 CD 3",
        "description": "(Physical DMG) Deals 90% AoE DMG to all enemies within 1-tile radius and inflicts Decreased Healing Received for 2 turns."
      },
      {
        "name": "Powerful Throw",
        "kind": "Active",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Physical DMG) Single-target ranged attack. Range 1-2."
      },
      {
        "name": "Shield Break",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Passive) Increases ATK when attacking enemies with a shield."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "recruited-assassin",
    "name": "Recruited Assassin",
    "rarity": "Rare",
    "role": "Breaker",
    "factions": [
      "Iria"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare assassin with pull (Hookshot) and multi-hit basic.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare assassin with pull (Hookshot) and multi-hit basic.",
    "build": {
      "basicAttack": "Dual Blade Strike",
      "reaction": "Counterattack",
      "skills": [
        "Hookshot",
        "Hunting Impulse",
        "Fancy Footwork"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Dual Blade Strike",
        "kind": "Basic",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals physical DMG 2 times. Melee range 1-1."
      },
      {
        "name": "Counterattack",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) When hit by active attack from front or side, performs basic attack if attacker in range, up to 1/round."
      },
      {
        "name": "Hunting Impulse",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target. Crit increases before attack. If target defeated, recovers 3 NRG. Melee 1-1."
      },
      {
        "name": "Hookshot",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Debuff) Selects 1 enemy in cross range, drags to self, inflicts debuff 1 turn. Range 1-4."
      },
      {
        "name": "Fancy Footwork",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Support) Takes less AoE DMG and gains dodge attempts for turns."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "recruited-guard",
    "name": "Recruited Guard",
    "rarity": "Rare",
    "role": "Defender",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare frontline guard with party physical cover (Global Guard).",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare frontline guard with party physical cover (Global Guard).",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Front Defense",
      "skills": [
        "Global Guard",
        "Defensive Stance",
        "Knock-Out Blow"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Basic Attack) Deals Physical DMG. Range 1-1."
      },
      {
        "name": "Front Defense",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Reaction) When hit by an active attack from the front, DMG taken decreased."
      },
      {
        "name": "Defensive Stance",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Support) Gains a shield based on HP and a buff for 2 turns."
      },
      {
        "name": "Global Guard",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip",
        "description": "(Support) Takes physical attacks for all other allies within 2 tiles. Gains buffs for 3 turns when activated."
      },
      {
        "name": "Knock-Out Blow",
        "kind": "Active",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device tooltip partial OCR",
        "description": "(Physical DMG) Single-target attack dealing DMG and inflicting a debuff for 1 turn. Range 1-1."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  },
  {
    "slug": "recruited-pikeman",
    "name": "Recruited Pikeman",
    "rarity": "Rare",
    "role": "Destroyer",
    "factions": [
      "The Union"
    ],
    "move": 3,
    "highJump": 2,
    "lowJump": 2,
    "summary": "Rare pikeman with line AoE shieldbreak.",
    "pros": [
      "Client-verified skill names",
      "See skill table"
    ],
    "howToUse": "Rare pikeman with line AoE shieldbreak.",
    "build": {
      "basicAttack": "Slash",
      "reaction": "Counterattack",
      "skills": [
        "Shieldbreak Jab",
        "Crumbling Smash",
        "Rupture Armor"
      ],
      "weaponSlug": "newborn-blade",
      "trinketSlug": "focus-lens",
      "tarotSlug": "temperance"
    },
    "skillPriority": [
      {
        "name": "Slash",
        "kind": "Basic",
        "stars": 2,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Basic Attack) Deals Physical DMG. Range 1-1."
      },
      {
        "name": "Counterattack",
        "kind": "Reaction",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Reaction) Front/side hit triggers basic attack counter, 1/round."
      },
      {
        "name": "Shieldbreak Jab",
        "kind": "Active",
        "stars": 5,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) AoE in target direction up to 4 tiles, inflicts debuff 2 turns."
      },
      {
        "name": "Crumbling Smash",
        "kind": "Active",
        "stars": 4,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Physical DMG) Single-target. Gains a buff before attacking. Range 1-1."
      },
      {
        "name": "Rupture Armor",
        "kind": "Passive",
        "stars": 3,
        "nrg": "—",
        "cd": "—",
        "note": "device",
        "description": "(Passive) Chance to inflict armor-break debuff for 2 turns before single-target attack."
      }
    ],
    "starPriority": "See client stars",
    "lastUpdated": "2026-08-02",
    "tier": {
      "overall": "C",
      "single": "B",
      "multi": "B",
      "reroll": "C"
    },
    "synergies": []
  }
] as Character[];

export function getDeviceOcrMap(): Record<string, DeviceOcrPartial> {
  return Object.fromEntries(DEVICE_OCR_REFINED.map((c) => [c.slug, c]));
}

export function getDeviceOcrCharacterMap(): Record<string, Character> {
  return Object.fromEntries(DEVICE_OCR_CHARACTERS.map((c) => [c.slug, c]));
}
